### ISSUE TITLE
Version 0.1.6 is missing builds for some platforms

### ISSUE THREAD

**Issue by bstadlbauer** [vincentsarago/color-operations#15]
Hi!

Whilst updating `color-operations` today, I've noticed that `0.1.6` seems to be missing a source distribution as well as wheels for some platforms (any besides `manylinux`; found [here](https://pypi.org/project/color-operations/0.1.6/#files)). 
I've poked around past action runs and the only suspicious one I've found was [this one](https://github.com/vincentsarago/color-operations/actions/runs/11211654137/job/31161188995), where it seems the `upload_pypi` step has failed. 

From what I've seen you've fixed the broken piece - would it be possible to create a new release there (or upload the missing artifacts manually). 
Happy to help in case there's anything I can do. 

Thanks for all the great geospatial tooling you've built!

**Comment by vincentsarago** [comment]
yeah I had issue with the CI with some outdated action but I though I solved it 🤷 

If it's only the source distribution that is missing, I'm sure I can upload it manually

**Comment by vincentsarago** [comment]
well maybe I'll just cut a new release

**Comment by vincentsarago** [comment]
<img width="858" alt="Screenshot 2024-10-09 at 1 50 47 PM" src="https://github.com/user-attachments/assets/933dc6a9-fbb0-4d92-b34f-7b4ea34f564d">

I've manually uploaded the source and wheels distributions

we should be all good now 

thanks for the report @bstadlbauer 🙏

**Comment by bstadlbauer** [comment]
Thank you for the quick turn-around 🙇
